# Example notebook using the package MPC_tuner

This notebook shows the use of the python package MPC_tuner that helps determining admissible NMPC parameters settings given a computation target. The methodology and the package are described in the paper 

#### M. Alamir, A Framework and a python-package for real-time N/PC parameters setting   http://arxiv.org/abs/2309.17238. 2023.

(See also the readme file in the git repository).

In [1]:
import numpy as np
from MPC_tuner import Design_MPC, Sigma, generate_A, OptimPar
from user_defined_pvtol import pvtol

# Generate the set of scenarios
#--------------------------------------------------
# Here, a small number of batch of small size is used for the illustration.
# replace by nb=30, nsb=10 to conform to the paper

nb, nsb = 5, 10  
A = generate_A(pvtol, nb, nsb)

# Generate the set of candidate sigma's
#--------------------------------------------------
# replace by N_trial=100 to conform to the paper 

N_trials = 25   
S = [Sigma() for _ in range(N_trials)]

# Set the Design meta-parameters and run the Design
#--------------------------------------------------
optim_par = OptimPar(gam=0.98, c_max=0.1,
                     dev_acc=1.0, T=0.5)

R_design_log = Design_MPC(pvtol, S, A, optim_par)

-------------
inspecting config #0 for the set A[0]
-------------
Dichotomy on: [0, 1]
Dichotomy on: [0, 0.5]
Dichotomy on: [0.25, 0.5]
Dichotomy on: [0.25, 0.375]
Dichotomy on: [0.25, 0.3125]
--------- current situation --------
[[0.00000000e+00 2.50000000e-01 6.17824116e+02]]
------------------------------------
-------------
inspecting config #1 for the set A[0]
-------------
Dichotomy on: [0, 1]
Dichotomy on: [0.5, 1]
Dichotomy on: [0.5, 0.75]
Dichotomy on: [0.625, 0.75]
Dichotomy on: [0.625, 0.6875]
--------- current situation --------
[[0.00000000e+00 2.50000000e-01 6.17824116e+02]
 [1.00000000e+00 6.56250000e-01            inf]]
------------------------------------
-------------
inspecting config #2 for the set A[0]
-------------
Dichotomy on: [0, 1]
Dichotomy on: [0.5, 1]
Dichotomy on: [0.5, 0.75]
Dichotomy on: [0.625, 0.75]
Dichotomy on: [0.6875, 0.75]
--------- current situation --------
[[0.00000000e+00 2.50000000e-01 6.17824116e+02]
 [1.00000000e+00 6.56250000e-01          

Dichotomy on: [0, 1]
Dichotomy on: [0, 0.5]
Dichotomy on: [0, 0.25]
Dichotomy on: [0, 0.125]
Dichotomy on: [0, 0.0625]
--------- current situation --------
[[0.00000000e+00 2.50000000e-01 6.17824116e+02]
 [1.00000000e+00 6.56250000e-01            inf]
 [2.00000000e+00 6.87500000e-01            inf]
 [3.00000000e+00 2.81250000e-01            inf]
 [4.00000000e+00 9.37500000e-02            inf]
 [5.00000000e+00 6.87500000e-01            inf]
 [6.00000000e+00 0.00000000e+00            inf]
 [7.00000000e+00 6.25000000e-01            inf]
 [8.00000000e+00 7.18750000e-01            inf]
 [9.00000000e+00 0.00000000e+00            inf]
 [1.00000000e+01 6.25000000e-01            inf]
 [1.10000000e+01 4.37500000e-01 1.20528639e+02]
 [1.20000000e+01 7.81250000e-01 2.51065374e+03]
 [1.30000000e+01 3.12500000e-02            inf]
 [1.40000000e+01 3.12500000e-02 1.31665318e+02]]
------------------------------------
-------------
inspecting config #15 for the set A[0]
-------------
Dichotomy on: [0, 1

Dichotomy on: [0, 1]
Dichotomy on: [0.5, 1]
Dichotomy on: [0.75, 1]
Dichotomy on: [0.75, 0.875]
Dichotomy on: [0.75, 0.8125]
--------- current situation --------
[[0.00000000e+00 2.50000000e-01 6.17824116e+02]
 [1.00000000e+00 6.56250000e-01            inf]
 [2.00000000e+00 6.87500000e-01            inf]
 [3.00000000e+00 2.81250000e-01            inf]
 [4.00000000e+00 9.37500000e-02            inf]
 [5.00000000e+00 6.87500000e-01            inf]
 [6.00000000e+00 0.00000000e+00            inf]
 [7.00000000e+00 6.25000000e-01            inf]
 [8.00000000e+00 7.18750000e-01            inf]
 [9.00000000e+00 0.00000000e+00            inf]
 [1.00000000e+01 6.25000000e-01            inf]
 [1.10000000e+01 4.37500000e-01 1.20528639e+02]
 [1.20000000e+01 7.81250000e-01 2.51065374e+03]
 [1.30000000e+01 3.12500000e-02            inf]
 [1.40000000e+01 3.12500000e-02 1.31665318e+02]
 [1.50000000e+01 3.12500000e-02            inf]
 [1.60000000e+01 5.00000000e-01 1.16235064e+02]
 [1.70000000e+01 7.500

In [2]:
R_design_log.df

kappa  N_pred  n_steps  n_ctr      rho_cstr   rho_final   tau  tau_u  \
11      9       6        8      4  8.133070e+06    8.005414  0.02   0.18   
12      2       7        2      2  9.729466e+06  477.360321  0.02   0.04   
16      2       5        2      6  8.909096e+06    2.951172  0.02   0.04   

    max_iter          cost    alpha  
11        11    653.732723  0.43750  
12        12  12289.175285  0.78125  
16         5    554.997559  0.50000

In [10]:
import pandas as pd
pd.DataFrame(R_design_log.n_excluded, 
             columns=['Number of excluded congiguration at batch number'], 
             index=[f'Batch #{i+1}' for i in range(len(R_design_log.n_excluded))])

Number of excluded congiguration at batch number
Batch #1                                                19
Batch #2                                                21
Batch #3                                                22
Batch #4                                                22
Batch #5                                                22